engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
      - 22c29059ae6bb876ee678dfad3c26ec4
ratings:
  paths:
    - "**.php"
exclude_paths:
  - .settings/
  - build/
  - tests/
  - vendor/
